package com.somniuss.controller.concrete;

public enum CommandName {
	DO_AUTH, DO_REGISTRATION, DO_MAKE_USER_AUTHOR, DO_ADD_SOUND,

	GO_TO_INDEX_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_AUTHOR_REGISTRATION_PAGE,

	GO_TO_AUTHOR_PAGE, GO_TO_MAIN_PAGE, GO_TO_GLITCH_PAGE, GO_TO_ATMOSPHERE_PAGE,

	NO_SUCH_COMMAND, LOG_OUT

}
